# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятия', 'verbose_name_plural': 'Мероприятие'},
        ),
        migrations.RenameField(
            model_name='event_user',
            old_name='book',
            new_name='event',
        ),
    ]
